[package]
name = "rtmp_message"
version = "0.1.0"
authors = ["KallDrexx <me@mshapiro.net>"]

[dependencies]
byteorder = "0.5.3"
quick-error = "1.1.0"
rtmp_time = { path = "../rtmp_time" }
amf0 = { path = "../amf0" }