[package]
name = "rtmp_chunk_io"
version = "0.1.0"
authors = ["KallDrexx <me@mshapiro.net>"]

[dependencies]
log = "0.3.6"
byteorder = "0.5.3"
quick-error = "1.1.0"
rtmp_time = { path = "../rtmp_time" }
rtmp_message = { path = "../rtmp_message" }